"""
Columns name in DB
"""

AGE_CERTIFICATION = 'age_certification'
CHARACTER = 'character'
DURATION = 'duration'
GENRE = 'genres'
FILM_ID = 'film_id'
IMDB_ID = 'imdb_id'
IMDB_SCORE = 'imdb_score'
IMDB_VOTES = 'imdb_votes'
INDEX = 'index'
MAIN_GENRE = 'main_genre'
MAIN_PRODUCTION = 'main_production'
NAME = 'name'
NUMBER_OF_SEASONS = 'number_of_seasons'
NUMBER_OF_VOTES = 'number_of_votes'
PERSON_ID = 'person_id'
PRODUCTION_COUNTRIES = 'production_countries'
RELEASE_YEAR = 'release_year'
ROLE = 'role'
RUNTIME = 'runtime'
SCORE = 'score'
SEASONS = 'seasons'
TITLE = 'title'
TYPE = 'type'
